<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<HTML>
<HEAD>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html;charset=windows-1252">
<TITLE></TITLE>
</HEAD>
<BODY>

<TABLE WIDTH=100%>
<TR><TD WIDTH=0></TD><TH WIDTH=16%></TH><TH WIDTH=11%></TH><TH WIDTH=2%></TH><TH WIDTH=11%></TH><TH WIDTH=7%></TH><TH WIDTH=7%></TH><TH WIDTH=2%></TH><TH WIDTH=10%></TH><TH WIDTH=0%></TH><TH WIDTH=3%></TH><TH WIDTH=3%></TH><TH WIDTH=10%></TH><TH WIDTH=3%></TH><TH WIDTH=13%></TH><TH WIDTH=2%></TH></TR>
  <TR><TD HEIGHT=96></TD></TR>
  <TR><TD HEIGHT=34></TD><TD></TD><TD COLSPAN=4 NOWRAP VALIGN=TOP><TABLE CELLSPACING=0 WIDTH=100% BORDER=1 BORDERCOLOR=FFFFFF><TR><TD><FONT FACE="Arial" SIZE=4><B>Sri Durga Stores</B></FONT></TD></TR></TABLE></TD><TD COLSPAN=5 NOWRAP VALIGN=TOP><FONT FACE="Rovisuam" SIZE=5>Jh nqxkZ</FONT></TD></TR>
  <TR><TD HEIGHT=20></TD><TD></TD><TD COLSPAN=10 NOWRAP VALIGN=TOP><FONT FACE="@Batang" SIZE=2><B>70/71,  Dhatkidih Market ,Jamshedpur-831005</B></FONT></TD><TD COLSPAN=4 NOWRAP VALIGN=TOP><FONT FACE="Batang" SIZE=1><B>Phone :2220007,2225007</B></FONT></TD></TR>
  <TR><TD HEIGHT=19></TD><TD></TD><TD COLSPAN=2 NOWRAP VALIGN=TOP><FONT FACE="Arial Narrow" SIZE=2><B>Customer Id</B></FONT></TD><TD COLSPAN=8 NOWRAP VALIGN=TOP><FONT FACE="Arial Narrow" SIZE=2><B>Customer Name</B></FONT></TD></TR>
  <TR><TD HEIGHT=19></TD><TD></TD><TD COLSPAN=2 NOWRAP VALIGN=TOP><FONT FACE="Batang" SIZE=1>10</FONT></TD><TD COLSPAN=8 NOWRAP VALIGN=TOP><FONT FACE="Batang" SIZE=1>Mr.krishna Babu</FONT></TD></TR>
  <TR><TD HEIGHT=19></TD><TD></TD><TD COLSPAN=2 NOWRAP VALIGN=TOP><FONT FACE="Arial Narrow" SIZE=2><B>Date</B></FONT></TD><TD NOWRAP VALIGN=TOP><FONT FACE="Arial Narrow" SIZE=2><B><DIV ALIGN=RIGHT>Total</DIV></B></FONT></TD><TD COLSPAN=2 NOWRAP VALIGN=TOP><FONT FACE="Arial Narrow" SIZE=2><B><DIV ALIGN=RIGHT>Payment</DIV></B></FONT></TD><TD COLSPAN=3 NOWRAP VALIGN=TOP><FONT FACE="Arial Narrow" SIZE=2><B><DIV ALIGN=RIGHT>Balance</DIV></B></FONT></TD><TD COLSPAN=3 NOWRAP VALIGN=TOP><FONT FACE="Arial Narrow" SIZE=2><B><DIV ALIGN=RIGHT>Adjustment</DIV></B></FONT></TD><TD COLSPAN=2 NOWRAP VALIGN=TOP><FONT FACE="Arial Narrow" SIZE=2><B><DIV ALIGN=RIGHT>Net Amount</DIV></B></FONT></TD></TR>
  <TR><TD HEIGHT=3></TD><TD></TD><TD COLSPAN=13 VALIGN=TOP><HR></TD></TR>
  <TR><TD HEIGHT=15></TD><TD></TD><TD NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=1 COLOR=FFFFFF>10</FONT></TD></TR>
  <TR><TD HEIGHT=19></TD><TD></TD><TD COLSPAN=2 NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=1>11/1/2004</FONT></TD><TD NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=1><DIV ALIGN=RIGHT>1703</DIV></FONT></TD><TD COLSPAN=2 NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=1><DIV ALIGN=RIGHT>0</DIV></FONT></TD><TD COLSPAN=3 NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=1><DIV ALIGN=RIGHT>1703</DIV></FONT></TD><TD COLSPAN=3 NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=1><DIV ALIGN=RIGHT>0</DIV></FONT></TD><TD COLSPAN=2 NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=1><DIV ALIGN=RIGHT>1703</DIV></FONT></TD></TR>
  <TR><TD HEIGHT=15></TD><TD></TD><TD NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=1 COLOR=FFFFFF>10</FONT></TD></TR>
  <TR><TD HEIGHT=19></TD><TD></TD><TD COLSPAN=2 NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=1>11/12/2004</FONT></TD><TD NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=1><DIV ALIGN=RIGHT>417</DIV></FONT></TD><TD COLSPAN=2 NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=1><DIV ALIGN=RIGHT>0</DIV></FONT></TD><TD COLSPAN=3 NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=1><DIV ALIGN=RIGHT>417</DIV></FONT></TD><TD COLSPAN=3 NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=1><DIV ALIGN=RIGHT>0</DIV></FONT></TD><TD COLSPAN=2 NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=1><DIV ALIGN=RIGHT>417</DIV></FONT></TD></TR>
  <TR><TD HEIGHT=15></TD><TD></TD><TD NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=1 COLOR=FFFFFF>10</FONT></TD></TR>
  <TR><TD HEIGHT=19></TD><TD></TD><TD COLSPAN=2 NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=1>12/1/2004</FONT></TD><TD NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=1><DIV ALIGN=RIGHT>1607</DIV></FONT></TD><TD COLSPAN=2 NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=1><DIV ALIGN=RIGHT>0</DIV></FONT></TD><TD COLSPAN=3 NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=1><DIV ALIGN=RIGHT>1607</DIV></FONT></TD><TD COLSPAN=3 NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=1><DIV ALIGN=RIGHT>0</DIV></FONT></TD><TD COLSPAN=2 NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=1><DIV ALIGN=RIGHT>1607</DIV></FONT></TD></TR>
  <TR><TD HEIGHT=0></TD><TD></TD><TD COLSPAN=13 VALIGN=TOP><HR></TD></TR>
  <TR><TD HEIGHT=38></TD><TD></TD><TD></TD><TD COLSPAN=2 NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=2><DIV ALIGN=RIGHT>3727</DIV></FONT></TD><TD COLSPAN=2 NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=2><DIV ALIGN=RIGHT>0</DIV></FONT></TD><TD COLSPAN=3 NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=3><B><DIV ALIGN=RIGHT>3727</DIV></B></FONT></TD><TD COLSPAN=3 NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=1><DIV ALIGN=RIGHT>0</DIV></FONT></TD><TD COLSPAN=2 NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=2><DIV ALIGN=RIGHT>3727</DIV></FONT></TD></TR>
  <TR><TD HEIGHT=19></TD><TD></TD><TD COLSPAN=5 NOWRAP VALIGN=TOP><FONT FACE="Arial Narrow" SIZE=2><B>Total Credit Payment (excluding this</B></FONT></TD><TD></TD><TD COLSPAN=7 NOWRAP VALIGN=TOP><FONT FACE="Arial Narrow" SIZE=2><B>Total Credit Payment (including this</B></FONT></TD></TR>
  <TR><TD HEIGHT=28></TD><TD></TD><TD COLSPAN=3 NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=3>500</FONT></TD><TD></TD><TD></TD><TD></TD><TD COLSPAN=2 NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=3><DIV ALIGN=RIGHT>500</DIV></FONT></TD></TR>
  <TR><TD HEIGHT=48></TD><TD></TD><TD COLSPAN=3 NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=3>3227</FONT></TD><TD></TD><TD></TD><TD></TD><TD NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=3><B><DIV ALIGN=RIGHT>3227</DIV></B></FONT></TD></TR>
  <TR><TD HEIGHT=19></TD><TD></TD><TD COLSPAN=3 NOWRAP VALIGN=TOP><FONT FACE="Batang" SIZE=1><B>Customer Address</B></FONT></TD></TR>
  <TR><TD HEIGHT=9></TD><TD></TD><TD COLSPAN=3 VALIGN=TOP><HR></TD></TR>
  <TR><TD HEIGHT=19></TD><TD></TD><TD NOWRAP VALIGN=TOP><FONT FACE="Batang" SIZE=1>Location</FONT></TD><TD COLSPAN=7 NOWRAP VALIGN=TOP><FONT FACE="Batang" SIZE=1>Shiv Mandir, Beldih</FONT></TD><TD></TD><TD COLSPAN=2 NOWRAP VALIGN=TOP><FONT FACE="Batang" SIZE=1>Phone   No.</FONT></TD></TR>
  <TR><TD HEIGHT=48></TD><TD></TD><TD></TD><TD></TD><TD></TD><TD></TD><TD></TD><TD></TD><TD></TD><TD></TD><TD></TD><TD COLSPAN=2 NOWRAP VALIGN=TOP><FONT FACE="Batang" SIZE=1>Mobile  No.</FONT></TD></TR>
  <TR><TD HEIGHT=15></TD><TD></TD><TD COLSPAN=4 NOWRAP VALIGN=TOP><FONT FACE="Batang" SIZE=1><B>Customer Signature</B></FONT></TD><TD></TD><TD></TD><TD></TD><TD></TD><TD COLSPAN=5 NOWRAP VALIGN=TOP><FONT FACE="Arial" SIZE=1><DIV ALIGN=RIGHT>Thursday, September 01, 2005</DIV></FONT></TD></TR>
  <TR><TD HEIGHT=494></TD></TR>
</TABLE>


</BODY>
</HTML>
<%
Dim Str
Str =Request.QueryString("x")
If Str<>Session("name")Or Str =""Then
Response.Redirect("index.asp")
End If
%>
